Add Single Use property to MesosSlave
d2iq-archive/jenkins-mesos-plugin pull request #16
Opened 2018-05-01 22:31 UTC by colin-msphere

Single-use agents are marked offline and then still wait for
idle timeout before being deleted. This commit adds a new
property to MesosSlave to mark single-use agents. This is
read during the retention check and used to mark a cluster
for deletion.

2018-05-02 16:29 UTC, gabrielhartmann commented on src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java
> +    this.singleUse = singleUse;
Let's put a lock around accessing this.

2018-05-02 16:29 UTC, gabrielhartmann requested changes
Lock needed, otherwise looks like a great idea.

2018-05-03 16:43 UTC, colin-msphere commented
@gabrielhartmann - this is ready for review again.

2018-05-08 16:15 UTC, gabrielhartmann approved these changes

2018-05-08 18:24 UTC, merged